# Use wildcard "*" to expose all endpoints
spring.application.name=myapp

#management.endpoints.web.exposure.include=health,info

# this is for all endpoints like beans,threaddump etc.
management.endpoints.web.exposure.include=* 

management.info.env.enabled=true

info.app.name=My Java AI App
info.app.description=It's an AI bot application
info.app.version=1.0.0