# Use wildcard "*" to expose all endpoints
spring.application.name=myapp

#defining application properties

brand.name=Zerodha
stock.name=Tata


#configuring server
server.port=5050

#setting application context path
server.servlet.context-path=/myapp